batch_size: 8
cfg: EMMNet_1
ckpt_dir: ./ckpts
criterion: GeneralizedDiceLoss
dataset: BraTSDataset
eps: 1.0e-05
gpu: '0'
is_out: true
mode: 1
name: EMMNet_1
net: MFNet
net_params:
  c: 4
  channels: 32
  groups: 1
  n: 32
  norm: sync_bn
  num_classes: 4
num_epochs: 950
opt: Adam
opt_params:
  amsgrad: true
  lr: 0.001
  weight_decay: 1.0e-05
postprocess: true
restore: model_last.pth
save_format: nii
save_freq: 1
seed: 2021
snapshot: true
start_iter: 0
test_data_dir: ./data2/liuxiaopeng/Data/BraTS2018/Test
test_transforms: Compose([ Pad((0, 0, 0, 5, 0)), NumpyType((np.float32, np.int64)),
  ])
train_data_dir: /media/omnisky/34B22D6336AC1687/Data/MICCAI_BraTS_2019_Data_Training
train_list: all.txt
train_transforms: Compose([ RandCrop3D((208,224,144)), RandomRotion(10), RandomIntensityChange((0.1,0.1)),
  RandomFlip(0), NumpyType((np.float32, np.int64)), ])
use_TTA: false
valid_data_dir: /media/omnisky/34B22D6336AC1687/Data/MICCAI_BraTS_2019_Data_Validation
valid_freq: 10
valid_list: valid.txt
verbose: true
weight_type: square
workers: 16
